### ISSUE TITLE
Error executing `paver develop_link`

### ISSUE THREAD

**Issue by cfobel** [ryanfobel/dmf_control_board#9]
```
(C:\MicroDrop) C: \software\wheeler repos\dmf-control-board-firmware>paver develop_link
---> pavement.develop_link
Check if Conda package is installed...
`dmf-control-board-firmware` package is not installed.
Install build and run-time Conda dependencies...
Fetching package metadata ...........
Solving package specifications: ..........
 
# All requested packages already installed.
# packages in environment at C:\MicroDrop:
#
conda-build               2.1.8                    py27_0    conda-forge
 
 
No handlers could be found for logger "conda_helpers"
 
 
Captured Task Output:
---------------------
 
---> pavement.develop_link
Check if Conda package is installed...
`dmf-control-board-firmware` package is not installed.
Install build and run-time Conda dependencies...
Traceback (most recent call last):
  File "C:\MicroDrop\lib\site-packages\paver\tasks.py", line 196, in _run_task
    return do_task()
  File "C:\MicroDrop\lib\site-packages\paver\tasks.py", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 123, in develop_link
    ch.development_setup(recipe_dir, verbose=True)
  File "C:\MicroDrop\lib\site-packages\conda_helpers\__init__.py", line 380, in development_setup
    rendered_recipe = conda_exec('render', recipe_dir, verbose=False)
  File "C:\MicroDrop\lib\site-packages\conda_helpers\__init__.py", line 306, in conda_exec
    raise RuntimeError(output)
RuntimeError: Error: no such directory: C:\software\wheeler repos\dmf-control-board-firmware\^\software^\wheeler repos^\dmf-control-board-firmware^
\.conda-recipe
```

**Comment by cfobel** [comment]
# Steps to reproduce #

 1. Clone `dmf-control-board-firmware` to the (exact) path: `C:\software\wheeler repos\dmf-control-board-firmware`
 2. Run the following commands in a Conda-activated command prompt:

       cd C:\software\wheeler repos\dmf-control-board-firmware
       paver develop_link

# Cause #

The issue seems to be a bug in the [`conda-build` tools][1] related to paths involving spaces.

# Workaround #

To work around the issue, rename the path to remove the space (i.e., `C:\software\wheeler-repos\dmf-control-board-firmware`, with `wheeler repos` replaced with `wheeler-repos`) and rerun the `paver develop_link` command.

Output from `paver develop_link` should be similar to the following:

```
(root) C:\software\wheeler-repos\dmf-control-board-firmware>paver develop_link
---> pavement.develop_link
Check if Conda package is installed...
`dmf-control-board-firmware` package is not installed.
Install build and run-time Conda dependencies...
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\Users\chris\Miniconda2:

The following packages will be UPDATED:

    conda-build: 2.1.8-py27_0 conda-forge --> 2.1.9-py27_0 conda-forge

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\Users\chris\Miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-cpp-1.46.1           |                0       137.6 MB  wheeler-microfluidics
    icu-58.1                   |            vc9_1        21.4 MB  conda-forge
    qt-5.6.2                   |            vc9_1        46.8 MB  conda-forge
    pyqt-5.6.0                 |           py27_0         3.0 MB  conda-forge
    matplotlib-2.0.0           |      np111py27_3         6.4 MB  conda-forge
    conda-helpers-0.4.0        |           py27_0          13 KB  wheeler-microfluidics
    dmf-control-board-firmware-develop-1.6.0|           py27_0           4 KB  wheeler-microfluidics
    ------------------------------------------------------------
                                           Total:       215.2 MB

The following NEW packages will be INSTALLED:

    dmf-control-board-firmware-develop: 1.6.0-py27_0      wheeler-microfluidics
    icu:                                58.1-vc9_1        conda-forge           [vc9]

The following packages will be UPDATED:

    matplotlib:                         2.0.0-np111py27_2 conda-forge           --> 2.0.0-np111py27_3 conda-forge
    pyqt:                               4.11.4-py27_2     conda-forge           --> 5.6.0-py27_0      conda-forge
    qt:                                 4.8.7-vc9_4       conda-forge           [vc9] --> 5.6.2-vc9_1       conda-forge           [vc9]

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-helpers:                      0.4.0-py27_0      local                 --> 0.4.0-py27_0      wheeler-microfluidics

The following packages will be DOWNGRADED due to dependency conflicts:

    boost-cpp:                          1.63.0-vc9_2      conda-forge           [vc9] --> 1.46.1-0          wheeler-microfluidics

Pruning fetched packages from the cache ...
Fetching packages ...
boost-cpp-1.46 100% |###############################| Time: 0:00:19   7.48 MB/s
icu-58.1-vc9_1 100% |###############################| Time: 0:00:04   4.77 MB/s
qt-5.6.2-vc9_1 100% |###############################| Time: 0:00:12   3.82 MB/s
pyqt-5.6.0-py2 100% |###############################| Time: 0:00:01   1.64 MB/s
matplotlib-2.0 100% |###############################| Time: 0:00:01   5.10 MB/s
conda-helpers- 100% |###############################| Time: 0:00:00 415.00 kB/s
dmf-control-bo 100% |###############################| Time: 0:00:00   1.52 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|                                             1 file(s) copied.
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

Link working firmware directories into Conda environment.
Link working Python directory into Conda environment...
added C:\software\wheeler-repos\dmf-control-board-firmware
completed operation for: C:\software\wheeler-repos\dmf-control-board-firmware

------------------------------------------------------------------------
Finished

(root) C:\software\wheeler-repos\dmf-control-board-firmware>
```

# TODO #

Track down the root cause of the issue in `conda-build` tools.


[1]: https://github.com/conda/conda-build
